---
development:
  dialect: postgres
  database: rally_development
  user: postgres
  password: mysecretpassword
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:mysecretpassword@127.0.0.1:5432/rally_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/rally_production?sslmode=disable"}}
